export const REQUEST_POKEMONS = 'REQUEST_POKEMONS';

export const RECEIVE_POKEMONS = 'RECEIVE_POKEMONS';

export const REQUEST_CAUGHT_POKEMONS = 'REQUEST_CAUGHT_POKEMONS';

export const RECEIVE_CAUGHT_POKEMONS = 'RECEIVE_CAUGHT_POKEMONS';

export const CATCH_POKEMON_REQUEST = 'CATCH_POKEMON_REQUEST';

export const POKEMON_TO_CAUGHT = 'POKEMON_TO_CAUGHT';